/**
 * add DIRECTORYNAME
 */
export const ADD_NEW_IMPORT_FROM_MAXIMO = "ADD_NEW_IMPORT_FROM_MAXIMO"
export const ADD_IMPORT_FROM_MAXIMO_SUCCESS = "ADD_IMPORT_FROM_MAXIMO_SUCCESS"
export const ADD_IMPORT_FROM_MAXIMO_FAIL = "ADD_IMPORT_FROM_MAXIMO_FAIL"
