/* WORKORDER_INSPECTIONS */

export const GET_WORKORDER_INSPECTIONS = "GET_WORKORDER_INSPECTIONS"
export const GET_WORKORDER_INSPECTIONS_SUCCESS =
  "GET_WORKORDER_INSPECTIONS_SUCCESS"
export const GET_WORKORDER_INSPECTIONS_FAIL = "GET_WORKORDER_INSPECTIONS_FAIL"

export const GET_WORKORDER_INSPECTIONS_VIEW = "GET_WORKORDER_INSPECTIONS_VIEW"
export const GET_WORKORDER_INSPECTIONS_VIEW_SUCCESS =
  "GET_WORKORDER_INSPECTIONS_VIEW_SUCCESS"
export const GET_WORKORDER_INSPECTIONS_VIEW_FAIL =
  "GET_WORKORDER_INSPECTIONS_VIEW_FAIL"

/**
 * add WORKORDER_INSPECTION
 */
export const ADD_NEW_WORKORDER_INSPECTION = "ADD_NEW_WORKORDER_INSPECTION"
export const ADD_WORKORDER_INSPECTION_SUCCESS =
  "ADD_WORKORDER_INSPECTION_SUCCESS"
export const ADD_WORKORDER_INSPECTION_FAIL = "ADD_WORKORDER_INSPECTION_FAIL"

/**
 * Edit WORKORDER_INSPECTION
 */
export const UPDATE_WORKORDER_INSPECTION = "UPDATE_WORKORDER_INSPECTION"
export const UPDATE_WORKORDER_INSPECTION_SUCCESS =
  "UPDATE_WORKORDER_INSPECTION_SUCCESS"
export const UPDATE_WORKORDER_INSPECTION_FAIL =
  "UPDATE_WORKORDER_INSPECTION_FAIL"

/**
 * Delete WORKORDER_INSPECTION
 */
export const DELETE_WORKORDER_INSPECTION = "DELETE_WORKORDER_INSPECTION"
export const DELETE_WORKORDER_INSPECTION_SUCCESS =
  "DELETE_WORKORDER_INSPECTION_SUCCESS"
export const DELETE_WORKORDER_INSPECTION_FAIL =
  "DELETE_WORKORDER_INSPECTION_FAIL"
