/* DIRECTORYNAMES */

export const GET_DIRECTORYNAMES = "GET_DIRECTORYNAMES"
export const GET_DIRECTORYNAMES_SUCCESS = "GET_DIRECTORYNAMES_SUCCESS"
export const GET_DIRECTORYNAMES_FAIL = "GET_DIRECTORYNAMES_FAIL"

export const GET_DIRECTORYNAMES_VIEW = "GET_DIRECTORYNAMES_VIEW"
export const GET_DIRECTORYNAMES_VIEW_SUCCESS = "GET_DIRECTORYNAMES_VIEW_SUCCESS"
export const GET_DIRECTORYNAMES_VIEW_FAIL = "GET_DIRECTORYNAMES_VIEW_FAIL"

/**
 * add DIRECTORYNAME
 */
export const ADD_NEW_DIRECTORYNAME = "ADD_NEW_DIRECTORYNAME"
export const ADD_DIRECTORYNAME_SUCCESS = "ADD_DIRECTORYNAME_SUCCESS"
export const ADD_DIRECTORYNAME_FAIL = "ADD_DIRECTORYNAME_FAIL"

/**
 * Edit DIRECTORYNAME
 */
export const UPDATE_DIRECTORYNAME = "UPDATE_DIRECTORYNAME"
export const UPDATE_DIRECTORYNAME_SUCCESS = "UPDATE_DIRECTORYNAME_SUCCESS"
export const UPDATE_DIRECTORYNAME_FAIL = "UPDATE_DIRECTORYNAME_FAIL"

/**
 * Delete DIRECTORYNAME
 */
export const DELETE_DIRECTORYNAME = "DELETE_DIRECTORYNAME"
export const DELETE_DIRECTORYNAME_SUCCESS = "DELETE_DIRECTORYNAME_SUCCESS"
export const DELETE_DIRECTORYNAME_FAIL = "DELETE_DIRECTORYNAME_FAIL"
